import {
  Laptop,
  Smartphone,
  Tablet,
  Headphones,
  Camera,
  Gamepad2,
  Keyboard,
  Watch,
  Monitor,
  Printer,
  BatteryCharging,
  HardDrive,
  Activity,
  Glasses,
  Aperture,
  Mic,
  Speaker,
  Gamepad,
  Cpu,
  Joystick,
  Zap,
} from 'lucide-react';

export const categoryIconMap: Record<string, React.ElementType> = {
  Accessories: Keyboard,
  Audio: Headphones,
  'Cameras & Drones': Camera,
  'Computers & Laptops': Laptop,
  Gaming: Gamepad2,
  'Phones & Tablets': Smartphone,
  Wearables: Watch,
  'Mobile Phones': Smartphone,
  'SIM Cards & Numbers': Zap,
  Tablets: Tablet,
  Desktops: Monitor,
  Laptops: Laptop,
  Monitors: Monitor,
  'Printers & Scanners': Printer,
  'Cases & Covers': Keyboard,
  'Power Banks': BatteryCharging,
  'Storage (USB/SSD)': HardDrive,
  'Fitness Trackers': Activity,
  'Smart Watches': Watch,
  'VR Headsets': Glasses,
  'Action Cameras': Camera,
  'Digital Cameras': Camera,
  Drones: Aperture,
  Lenses: Aperture,
  Headphones: Headphones,
  Microphones: Mic,
  Speakers: Speaker,
  Consoles: Gamepad,
  'PC Components': Cpu,
  'Video Games': Joystick,
  'Gaming Accessories': Gamepad2,
  'Cables & Chargers': Zap,
};
